#!/bin/bash
START() {
  lan="$1" 
  sudo mkdir -p /dorry_data/bypass_conf
  sudo cp `pwd`/white/* /dorry_data/bypass_conf/
  docker run -itd --privileged --restart=always --cap-add=NET_ADMIN --net=host -v /dorry_data/bypass_conf:/bypass -e LAN=$lan -e PORT_1=1080 -e PORT_2=1090 --name router_bypass dorrypizza/bypass:test
}

case "$1" in
  start)
    lan="$2"
    [ "$lan" == "" ] && echo "Usage: $0 {start eth1|stop eth1|restart eth1|status}" && exit
    START $lan
    ;;

  stop)
    lan="$2"
    [ "$lan" == "" ] && echo "Usage: $0 {start eth1|stop eth1|restart eth1|status}" && exit
    docker exec -it router_bypass ./clean-rule $lan
    docker exec -it router_bypass ./clean-ipset
    docker rm -f router_bypass
    sudo rm /dorry_data/bypass_conf/*
    ;;

  restart)
    lan="$2"
    [ "$lan" == "" ] && echo "Usage: $0 {start eth1|stop eth1|restart eth1|status}" && exit
    docker exec -it router_bypass ./clean-rule $lan
    docker exec -it router_bypass ./clean-ipset
    docker rm -f router_bypass
    sudo rm /dorry_data/bypass_conf/*

    START $lan
    ;;

  status)
    echo ""
    echo "---------------------------- bypass status ---------------------------"
    docker ps -a | grep bypass
    sudo iptables -t nat -L -vn
    ;; 

  *)
    echo $"Usage: $0 {start eth1|stop eth1|restart eth1|status}"
    exit 1

esac
